In [9]:
import pandas as pd
indicators = pd.read_csv("indicators.csv", sep = ",")

In [10]:
indicators

GDP_CAPITA       BALANCE  MANUFACTURE_IMPORTS  SERVICE_EMPLOYMENT  \
0     2082.392197  5.745537e+09            45.220595           38.410000   
1    13498.138167  3.381321e+09            47.511441           42.970001   
2    11908.537607  7.160573e+09            65.790506           59.220001   
3    22612.704331  1.027254e+09            65.790506           55.347987   
4    22612.704331  1.027254e+09            68.294552           55.347987   
..            ...           ...                  ...                 ...   
162   7252.137355  6.866855e+09            79.924678           50.689999   
163   3166.980897  2.396779e+08            65.790506           28.969999   
164   9776.819500 -1.653963e+10            76.796309           34.660000   
165   3605.676095 -5.139038e+08            64.204290           39.290001   
166   2556.793484  1.938391e+09            58.113619           27.230000   

     FOREIGN_INVESTMENT  FUEL_EXPORTS  GROSS_SAVINGS  INFLATION  \
0              0.661572     10.213181      23.100673   0.626149   
1              7.946351      1.662666      16.547233   2.028060   
2              0.838207     15.189064      40.205962   4.269990   
3             -5.730436     15.189064      23.100673   4.369297   
4             -5.730436      0.013639      23.100673   4.369297   
..                  ...           ...            ...        ...   
162            1.186869     24.939491      35.607162   4.369297   
163            4.108664     15.189064      39.416867   2.330964   
164            5.021022      1.613913      23.100673   3.539628   
165            1.552314      1.024689      41.825828   7.494572   
166            3.962704      1.010572       2.358411  10.618866   

     EXPORT_TELECOM  LIFE_EXPECTANCY  ...  FERTILITY_RATE  \
0         65.516134        64.486000  ...        4.473000   
1         29.850758        78.458000  ...        1.617000   
2         62.916580        76.693000  ...        3.023000   
3         33.265259        72.550799  ...        2.648885   
4         33.265259        72.550799  ...        2.648885   
..              ...              ...  ...             ...   
162       10.875411        71.573000  ...        2.604000   
163        3.288492        70.323000  ...        3.782000   
164       33.265259        75.317000  ...        2.049000   
165        7.516471        63.510000  ...        4.633000   
166       12.331765        61.195000  ...        3.615000   

     HUMAN_CAPITAL_INDEX  FEMALE_LABOR_FORCE  POPULATION_65_ABOVE  \
0               0.393489           21.741486             2.584927   
1               0.628666           42.720264            13.744736   
2               0.531994           19.849984             6.362497   
3               0.572202           41.915803             9.136007   
4               0.572202           41.915803             9.136007   
..                   ...                 ...                  ...   
162             0.572202           39.987940             4.419138   
163             0.444750           43.547789             3.640153   
164             0.687239           47.422656             7.274978   
165             0.391176           48.225372             2.099678   
166             0.461242           51.512789             2.939524   

     EDUCATION_EXPENDITURE  URBAN_POPULATION  CO2_EMISSIONS  ARMED_FORCE  \
0                 3.199790            25.495       0.351866     2.722970   
1                 4.518576            60.319       0.437493     0.643149   
2                 5.866350            72.629       0.863727     2.570824   
3                 4.518576            87.153       0.452589     1.212733   
4                 3.246720            88.062       0.155958     1.212733   
..                     ...               ...            ...          ...   
162               5.900000            50.478       1.171877     0.486005   
163               4.518576            25.274       0.215040     1.212733   
164               4.167450            35.91

In [3]:
import numpy as np

In [13]:
u, s, v = np.linalg.svd(indicators)

In [15]:
u.shape

(167, 167)

In [26]:
u

array([[-5.34011792e-03, -2.87034081e-02,  4.07145314e-03, ...,
        -9.07281151e-03,  4.29017961e-02,  4.69579837e-03],
       [-3.14272667e-03, -6.77344158e-04, -3.47096919e-02, ...,
        -7.86820159e-03,  2.07460943e-02, -3.99789981e-02],
       [-6.65530643e-03, -1.07319588e-01,  4.53820273e-03, ...,
        -7.20953855e-02, -1.17062062e-01, -1.66040725e-02],
       ...,
       [ 1.53725536e-02, -1.82355758e-02, -1.93202274e-02, ...,
         9.16302623e-01,  7.80070731e-03, -4.47659671e-02],
       [ 4.77641505e-04, -3.44359008e-02,  2.00940582e-03, ...,
         3.44826144e-03,  9.22381088e-01,  4.13561640e-03],
       [-1.80161311e-03, -1.74634652e-02, -8.63465683e-04, ...,
        -4.54032293e-02,  4.98388346e-03,  9.22673257e-01]])

In [17]:
s

array([1.07591942e+12, 2.19173396e+07, 3.86377098e+05, 1.32399821e+03,
       1.27755036e+03, 3.23247821e+02, 3.05005106e+02, 2.53429421e+02,
       2.12153909e+02, 1.91826168e+02, 1.20293014e+02, 1.04716475e+02,
       9.98716102e+01, 8.98189808e+01, 6.11866055e+01, 4.82472578e+01,
       1.83715710e+01, 1.61619197e+01, 8.53354927e+00, 3.56483186e+00,
       7.04884863e-01])

In [20]:
s.shape

(21,)

In [22]:
s **2

array([1.15760260e+24, 4.80369773e+14, 1.49287262e+11, 1.75297125e+06,
       1.63213493e+06, 1.04489154e+05, 9.30281147e+04, 6.42264716e+04,
       4.50092810e+04, 3.67972789e+04, 1.44704093e+04, 1.09655400e+04,
       9.97433852e+03, 8.06744932e+03, 3.74380070e+03, 2.32779789e+03,
       3.37514620e+02, 2.61207647e+02, 7.28214632e+01, 1.27080262e+01,
       4.96862669e-01])

In [21]:
v.shape

(21, 21)

In [24]:
v.T.shape

(21, 21)

In [25]:
indicators.index

RangeIndex(start=0, stop=167, step=1)